services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    VidarL\Bundle\IbexaUtil\:
        resource: '../../*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

